### ISSUE TITLE
Logs for IRC

### ISSUE THREAD

**Issue by jhasse** [JuliaLang/julialang.github.com#226]
I've noticed that the #julia channel on freenode hasn't any logs. I think this would be great as I often have to go offline and can't check if there have been answers in the meantime.

Can someone of the ops request an IRC logger? e. g. https://botbot.me/request/

See the following discussion on the julia-dev mailing list: https://groups.google.com/d/topic/julia-dev/idcSasbgBrk/discussion

**Comment by oxinabox** [comment]
IRC is now kinda implictly logged in Gitter due to the the Gitterbot cross posting between them
See: https://groups.google.com/forum/#!topic/julia-users/ImKYzqHXA90

Logs can be found in [Gitter Scrollback](https://gitter.im/JuliaLang/julia),
or the [archive ](https://gitter.im/JuliaLang/julia/archives/all)

More generally, for IRC it is fairly normal to just have a IRC session open all the time so you get scrollback (and logging if you want). Eg by running `irssi` inside of `screen` / `tmux`  on a linux server that you SSH into.
(or is that just me, and everyone I know IRL, on IRC?)

**Comment by ChrisRackauckas** [comment]
It's logged perfectly well via Gitter. I don't think this needs to be open anymore.

**Comment by jhasse** [comment]
> More generally, for IRC it is fairly normal to just have a IRC session open all the time so you get scrollback (and logging if you want). Eg by running irssi inside of screen / tmux on a linux server that you SSH into.
(or is that just me, and everyone I know IRL, on IRC?)

I think many people are using an GUI IRC client instead, like HexChat.

**Comment by ChrisRackauckas** [comment]
Yeah, applications like HexChat are pretty common. But I think that's beside the point. If the goal was to have a log for the #julia freenode, then Julia by default the GitterBot + Gitter's logging already provides that. Since the Gitter is by far more active than the freenode channel anyways and they are both connected, this serves as a good log for the main chat channel.

**Comment by sidgupta234** [comment]
What is the current status? I feel like we can close this one.

**Comment by ChrisRackauckas** [comment]
We definitely can.
