### ISSUE TITLE
annoyingly missing orange dot in widely viewed benchmarks page

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julialang.github.com#236]
Moved from https://github.com/JuliaLang/julia/issues/11446:

http://julialang.org/benchmarks/
lacks an orange dot in the legend for rand_mat_stat
kind of sticks out like a sore thumb

Note last line of
![image](https://cloud.githubusercontent.com/assets/862530/7825201/f33d50b2-03d7-11e5-80c8-88404e7d6fec.png)

**Comment by espintos** [comment]
Seems to be some sort of bug with Gadfly.

Quick solution: removing line [26](https://github.com/JuliaLang/julialang.github.com/blob/master/benchmarks.jl#L26) from benchmarks.jl

    colorkey_swatch_shape = :circle,

solves the color problem, although the shape of the legend will be a square instead of a circle:

![pibtiuz](https://cloud.githubusercontent.com/assets/9314765/7827876/c39d9062-0402-11e5-9bf3-e5562201f3b0.png)

**Comment by dcjones** [comment]
[Fixed](https://github.com/dcjones/Gadfly.jl/commit/f8d5d3ccd248445e604b807fa39ea75a2ae94449) the bug in Gadfly.
