### ISSUE TITLE
Improve list of SoC projects

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julialang.github.com#339]
Reviewing our current list of [Summer of Code projects](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md), I think that some of the projects should be removed and others should be significantly revised or otherwise removed entirely. IMO the projects listed in Lists 1 and 2 are far too ambitious, vague or otherwise unsuitable for a SoC project of 2-3 developer-months.

## List 1: Projects which I think are unrealistic for SoC students to pursue and should be nixed

- [x] [Translations of Axiom to Julia](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#translation-of-axiom-to-julia). I don't see this as high priority, nor is this realistic to expect any usable product after just 2-3 developer-months, nor do we really have the mentors capable of supervising this project (which requires expert knowledge of computer algebra systems).

- [x] [Base Julia Restructuring](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#base-julia-restructuring). While this project needs doing, I do not think it is feasible for a summer student to do it. It's far too much work for a SoC, has little tangible product that a student can take ownership of, and whoever does this project will bear the brunt of being harangued against by the other developers as they adjust to the new base library structure.

## List 2: Projects worth doing but are too vague

Projects on this list have descriptions that are essentially "X is broken, fix it" or "I want X, Y, Z, three ponies, and a unicorn".

IMO these project descriptions should be whittled down in scope, so that SoC students can reasonably hope to finish something in 2-3 months, or otherwise axed.

- [x] [Writing high-performance, multithreaded kernels for image processing](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#writing-high-performance-multithreaded-kernels-for-image-processing) - the current description is vague and does not define any project of reasonable scope for a SoC. Taken literally, this project could easily be 1-n PhD's worth of work.

- [ ] [Better error reporting](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#better-error-reporting) - Worth doing, but vague.

- [ ] [C linter](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#c-linter) - Solving the memory leak problem via static analysis seems way too hard for a SoC project.

- [x] [Web stack / networking improvements](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#web-stack--networking-improvements) - a random grab bag that just says "it's all broken, fix it".

## List 3: Projects that could use cross-referencing to existing packages

This list of projects just need minor updates to the descriptions. If the authors referenced agree, I think these extant packages could be cross-referenced to existing project descriptions.

- [ ] [Dynamic distributed execution for data parallel tasks in Julia](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#dynamic-distributed-execution-for-data-parallel-tasks-in-julia) - could use a cross-reference to @shashi's [ComputeFramework.jl](https://github.com/shashi/ComputeFramework.jl)

- [x] [Syntax checker](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/ideas-page.md#syntax-checker) should probably be updated to reference @tonyhffong's [Lint.jl](https://github.com/tonyhffong/Lint.jl).

**Comment by ViralBShah** [comment]
I will put up concrete stuff for ComputeFramework.

**Comment by jiahao** [comment]
Thanks Viral!

**Comment by one-more-minute** [comment]
Thanks @jiahao for taking a really detailed look over these.

I think the web stuff can be broken down into:

* Support for new protocols / low level technologies – HTTP2 etc.
* Mid-level things like routing, cookie handling etc. – and making these independent but composable pieces (I like the Clojure/Ring model a lot here).
* Database interaction
* In general, getting to a polished state where it's easy to set up a webserver with some basic logic and serve some pages etc.

To some extent these can be done independently, but getting enough of each part working to have a really basic proof of concept (e.g. a simple jekyll-like server) would be a great project in itself. I'd be happy to mentor if there's no one better qualified, and I expect @shashi has some thoughts too.

**Comment by timholy** [comment]
@ViralBShah, do you want to edit the GPU project to incorporate recent efforts on ArrayFire? (Or will the work on ArrayFire likely make other efforts unnecessary?)

**Comment by ViralBShah** [comment]
I have been quite impressed with ArrayFire in general, since @ranjanan and I have been working with it in the last few weeks. It still does not have sparse capabilities (perhaps @pavanky can say if there is a plan), but our plan is to wrap up all of it and port the ArrayFire demos to Julia.

This may mean that our focus on GPU side can be more on native codegen going forward, and we may be ok on GPU libraries.

**Comment by ChrisRackauckas** [comment]
I just put a pull request for a different type of GPU computing project. While ArrayFire is nice, ultimately the ability take a vectorized Julia function and have it be solved on the GPU is required for building more in depth programs. Obviously this isn't hard to do with each function you write (i.e. just use CUDA.jl and write a kernal), but if someone wrote a wrapper which takes a Julia function to a C pointer, and has a CUDA kernal to simply divvy up the calculation in some smart manner and apply that function element-wise (a la  map, or MATLAB arrayfun, or R apply), then a lot of CUDA programming can be done within Julia. Using just this implementation, then many Julia implementations for standard functions on CuArrays also follow.

This project isn't too hard itself (the hardest part would be dealing with the function handle, the CUDA kernal is pretty simple) and some good results should be possible pretty quickly, making it a good candidate for SoC.

**Comment by ChrisRackauckas** [comment]
On the GPU side, what about a wrapper for CUSP? I know that sparse iterative solvers are on the menu on the CPU side, but one of the best uses for the GPU is linear algebra. Although we have cuSPARSE, that doesn't implement the common solvers like conjugate gradient and the like, and so someone who is looking to really use sparse linear algebra has to either implement it or wrap to CUSP themselves in a CUDA kernel.

Another thing that I think should be added is a better console in Juno Atom. Something to do with https://github.com/JunoLab/atom-ink/issues/20, but also the issue with progress bars like at https://github.com/JuliaLang/julia/issues/8064 and https://github.com/timholy/ProgressMeter.jl/issues/32. A good outcome could be a more responsive console that allows for showing a progress meter (that can be used on parallel operations), or simply putting the progress bar in some window not in the console (which I would prefer so other updates could print). That would immensely help usability.

Another idea is to fix up the GSL.jl wrapper since a lot of the functionality doesn't work, though I would prefer native Julia implementations for most of it.

Julia functions to ptx via the LLVM was also mentioned elsewere, but that might be difficult.

Depending on the release of Knights Landing, maybe some packages for usability / a standard Julia for implementing automatic offloading via MKL could be interesting projects.

**Comment by ViralBShah** [comment]
Cusp looks awesome. Have you used it? Is it reasonably ready to use and maintained?

**Comment by ChrisRackauckas** [comment]
@ViralBShah, I haven't used it yet (been meaning to), but I keep getting linked back to it. It's perfectly ready to use and is pretty stable with most of the new releases just matching new CUDA toolkits. [PETSc uses it as the basis for the GPU methods](http://www.mcs.anl.gov/petsc/features/gpus.html).

**Comment by timholy** [comment]
To clarify a previous point I made, I think the idea of Julia->LLVM->PTX would be awesome. It's just that I fear the number of people who could mentor such a project may be small, and it may be a big project. But with the right student/mentor combination, it could have huge impact.

Overall I'm enthusiastic about better GPU tooling.

**Comment by ChrisRackauckas** [comment]
Another thing that comes to mind is extending Julia's random number generation by making bindings to MKL VSL. These would most likely beat a native Julia implementation in terms of performance and would be very useful in scientific computing (especially once Knights Landing comes out and more things are offloaded/built with MKL). It wouldn't be too hard since they could use a lot of the implementation ideas from VML.jl.

**Comment by jiahao** [comment]
I believe we can close this now that GSoC project selection is well underway. Thank you everyone for their suggestions!

**Comment by eford** [comment]
Is there a way to indicate that one could be interested in serving as a
mentor for a specific project?
In may case, it's Native Julia solvers for ordinary differential equations.


On Tue, Apr 12, 2016 at 1:41 PM, Jiahao Chen <notifications@github.com>
wrote:

> I believe we can close this now that GSoC project selection is well
> underway. Thank you everyone for their suggestions!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julialang.github.com/issues/339#issuecomment-209023376>
>



-- 
Eric Ford
Professor of Astronomy & Astrophysics
Center for Exoplanets & Habitable Worlds
Center for Astrostatistics
Institute for CyberScience
Penn State Astrobiology Research Center
Pennsylvania State University

**Comment by jiahao** [comment]
@eford Yes; @MikeInnes or @shashi can invite you to participate on the Google Summer of Code website as a official mentor.
