### ISSUE TITLE
Update benchmarks for v0.6

### ISSUE THREAD

**Issue by musm** [JuliaLang/julialang.github.com#420]

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
lonely bump

**Comment by StefanKarpinski** [comment]
@Keno has recently gotten the machine we did benchmarking on back in action so this could be done now.

**Comment by ViralBShah** [comment]
It won't change anything, but needs to be current anyways.

**Comment by ararslan** [comment]
Has this been resolved? If not it should probably stay open for tracking purposes.

**Comment by grinsted** [comment]
I have made contributions to some of the Matlab microbenchmarks on Oct 23, 2015. These changes are still not reflected on the webpage https://github.com/JuliaLang/julialang.github.com/blob/master/_includes/benchmarks.html 

Updating might not change so much for the julia benchmarks, but it will change the results for matlab.

**Comment by ChrisRackauckas** [comment]
Bump, what about just doing this for v0.6?

**Comment by ViralBShah** [comment]
Yeah, let's just do it for 0.6. I wonder if we have docker containers with all the relevant software for the benchmarks. It is a bit of a pain to get the commercial licenses, which makes this exercise difficult.

**Comment by lobingera** [comment]
Would it make sense to share the effort - i only see two commercial tools there - and let people run a subset of the tests and combine?

**Comment by fredrikekre** [comment]
The benchmarks would not make any sense unless run on the same hardware though.

**Comment by lobingera** [comment]
If i'm not mistaken, the table lists relative performance to C. So if in a subset C, f77 and maybe go is included, alignment should be possible. If you run every benchmark on different HW, i agree with you, it's hard to come up with consistent numbers.

**Comment by tpapp** [comment]
Lacking convenient and semi-permanent access to commercial licenses (since benchmarks need to be rerun from time to time), I wonder if it would make sense to drop Matlab and Mathematica altogether. And possibly R and Octave, since they are straw men for benchmarks.

A table with C, Fortran, Python, Go, and possibly LUA, Java, and Javascript would still be very informative. Sometimes less is more.

**Comment by johnfgibson** [comment]
I'll try to take a shot at this in the coming week. I have academic licenses, a good Linux box to run them on,  and an interest in the benchmarking process. If others approve I'll try to add my 1d PDE benchmark, which I have running in most of the benchmark languages.

**Comment by johnfgibson** [comment]
I've made some progress and have gotten the benchmarks working again on all languages except Go and Scala. I've been documenting progress and posting benchmark plots at https://discourse.julialang.org/t/benchmark-for-latest-julia/5991/31 and have posted a pull request https://github.com/JuliaLang/julia/pull/23922

A couple things need to be resolved before updating the published benchmarks: poor performance of Fortran, Python, and R on rand_mat_mul (best guess is they're not linking to BLAS) and strangely good performance mandel for Java and Javascript. SciLua is quite impressive, beating Julia on quite a few of the benchmarks. 

But I think it'd be good to accept the pull request, which just gets the benchmarks running again, so that others can run the benchmarks and weigh in on the unresolved performance issues.

**Comment by johnfgibson** [comment]
Ok, it's good to go. [Pull request 643](https://github.com/JuliaLang/julialang.github.com/pull/643) brings the benchmark table, plot, and text on julialang.org up-to-date for 0.6.0 and current versions of other languages. 

There's a PR for the updates to the benchmark codes [#23922](https://github.com/JuliaLang/julia/pull/23922) languishing on JuliaLang/julia. I need to push a few more changes and squash the commits; will do that shortly.
