### ISSUE TITLE
Broken links to the Julia manual

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julialang.github.com#471]
A user at twitter reported broken links:

* https://twitter.com/MIsForMerkin/status/809488372746088448

The website links to:

* http://docs.julialang.org/en/stable/manual/parallel-computing/

But the correct links is:

* http://docs.julialang.org/en/stable/manual/parallel-computing.html

I also noticed that the widget that is used to choose versions is nowhere to be found, is this related? Should I change the links directly or are this automatically generated?

**Comment by MichaelHatherly** [comment]
Links should be fixed now on the old sphinx docs. Was due to using `make html` rather than `make dirhtml` for the sphinx builds. Document does not currently support a "dirhtml"-like build option, since building a site like that makes it difficult to view locally due to the folder structure; you have to run a server to navigate it properly. I personally prefer being able to view the same docs build locally or hosted without having to change anything, but if there's demand for it then we'll probably have to add it to Documenter.

> I also noticed that the widget that is used to choose versions is nowhere to be found, is this related? Should I change the links directly or are this automatically generated?

See discussion in https://github.com/JuliaLang/julialang.github.com/issues/463 about that.

**Comment by ViralBShah** [comment]
So close this issue?

**Comment by Ismael-VC** [comment]
I can confirm links are working again as usual, closing this, thank you Michael!
