### ISSUE TITLE
Benchmark plot looks rubbish on Firefox

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julialang.github.com#658]
![bench](https://user-images.githubusercontent.com/4098145/32137976-ce84cbac-bc2a-11e7-9cc5-f80e5221278e.png)

(but looks fine on my machine on chromium).  I think this is a Gadfly issue.  Maybe best to use a PNG instead of whatever the picture is?  

Cc: @johnfgibson

**Comment by johnfgibson** [comment]
@mauro3 Wow, that's terrible. What OS & kind of device are you using? 

That's an SVG graphic. It looks fine on FireFox and Chrome on my Linux laptop (openSUSE). I'm no expert on web standards, but I believe that scalable SVG is generally preferred over bitmap PNG because it adapts well to different pixel densities, resized windows, etc. But that above is a total mess. 

Not sure what to do here. I think we need to know how widepsread the problem is and have someone with better knowledge of web development make a call.

**Comment by mauro3** [comment]
Yep, terrible.  I use Arch Linux with Firefox 56.0.1 (64-bit).

**Comment by ararslan** [comment]
It looks normal to me on both FreeBSD and macOS with Firefox 56.0.2.

**Comment by mauro3** [comment]
Ok, sorry it was my fault(ish), I ran into this: https://stackoverflow.com/questions/29878587/firefox-doesnt-respect-font-size-in-svg-text
